# Generated by Django 5.2.8 on 2025-12-24 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_gedcomfile_user_alter_gedcomfile_file_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedGedcomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gedcom_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.gedcomfile')),
            ],
        ),
    ]
