# Generated by Django 5.2.8 on 2025-12-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_parsedgedcomdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedgedcomdata',
            name='home_person_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
