# Generated by Django 5.2.8 on 2025-12-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_gedcomfile_home_person_id_gedcomfile_is_processed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParsedGedcomData',
        ),
    ]
