# Generated by Django 6.0 on 2026-01-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_delete_parsedgedcomdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='gedcomfile',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
