# Generated by Django 6.0.2 on 2026-03-16 01:57

import apps.generator.models.gedcom_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_gedcomfile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gedcomfile',
            name='file',
            field=models.FileField(upload_to=apps.generator.models.gedcom_file.user_gedcom_upload_path),
        ),
    ]
