# Generated by Django 6.0 on 2026-01-17 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_gedcomfile_last_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('initial_translate_x', models.FloatField(default=0)),
                ('initial_translate_y', models.FloatField(default=0)),
                ('subject_translate_x', models.FloatField(default=0)),
                ('subject_translate_y', models.FloatField(default=0)),
                ('font_family', models.CharField(default='Arial', max_length=100)),
                ('primary_name_font_size', models.FloatField(default=113)),
                ('primary_info_font_size', models.FloatField(default=113)),
                ('default_stroke_width', models.FloatField(default=0.5)),
                ('stroke_antialias', models.BooleanField(default=True)),
                ('primary_font_color', models.CharField(default='black', max_length=20)),
                ('primary_birth_color', models.CharField(default='black', max_length=20)),
                ('primary_place_color', models.CharField(default='black', max_length=20)),
                ('primary_death_color', models.CharField(default='black', max_length=20)),
                ('primary_stroke_color', models.CharField(default='black', max_length=20)),
                ('primary_name_x', models.FloatField(default=0)),
                ('primary_name_y', models.FloatField(default=0)),
                ('primary_name_rotate', models.FloatField(default=-45)),
                ('primary_birth_x', models.FloatField(default=0)),
                ('primary_birth_y', models.FloatField(default=135)),
                ('primary_birth_rotate', models.FloatField(default=45)),
                ('primary_place_x', models.FloatField(default=0)),
                ('primary_place_y', models.FloatField(default=90)),
                ('primary_place_rotate', models.FloatField(default=-45)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chart Setting',
                'verbose_name_plural': 'Chart Settings',
            },
        ),
    ]
