# Generated by Django 6.0.2 on 2026-03-16 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_alter_gedcomfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GedcomShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('gedcom_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='generator.gedcomfile')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gedcom_shared', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gedcom_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['gedcom_file'], name='generator_g_gedcom__ea0147_idx'), models.Index(fields=['shared_with'], name='generator_g_shared__ca5eda_idx')],
                'unique_together': {('gedcom_file', 'shared_with')},
            },
        ),
    ]
