"""
DID utilities for Namecharts (aka iyou_name).

This module provides DID generation and verification functionality using the Rust backend
when available, with Python fallback. For VC issuance, it uses didkit with the
Rust-generated DID.
"""

import json
import logging
import os
from typing import Dict, Optional

try:
    from apps.users.did_rust_wrapper import generate_did as wrapper_generate_did
    from apps.users.did_rust_wrapper import verify_vc as wrapper_verify_vc

    DID_BACKEND_AVAILABLE = True
except ImportError:
    DID_BACKEND_AVAILABLE = False

logger = logging.getLogger(__name__)

DID_BACKEND = os.environ.get("DID_BACKEND", "python")

DIDKIT_AVAILABLE = False
try:
    import didkit

    DIDKIT_AVAILABLE = True
except ImportError:
    logger.warning("didkit not available - VC issuance will use mock implementation")


def generate_did(method: str = "key") -> str:
    """
    Generate a new DID.

    Args:
        method: The DID method to use (e.g., "key").

    Returns:
        The generated DID string.
    """
    if DID_BACKEND == "rust" and DID_BACKEND_AVAILABLE:
        return wrapper_generate_did(method)

    if DIDKIT_AVAILABLE and method == "key":
        try:
            key = didkit.generateEd25519Key()
            did = didkit.keyToDID("key", key)
            return did
        except Exception as e:
            logger.warning(f"didkit DID generation failed: {e}")

    import uuid

    return f"did:key:mock-{uuid.uuid4().hex[:16]}"


def verify_vc(vc_json: str) -> bool:
    """
    Verify a verifiable credential.

    Args:
        vc_json: The VC as a JSON string.

    Returns:
        True if valid, False otherwise.
    """
    if DID_BACKEND == "rust" and DID_BACKEND_AVAILABLE:
        return wrapper_verify_vc(vc_json)

    if DIDKIT_AVAILABLE:
        try:
            result = didkit.verifyCredential(
                vc_json, '{"proofPurpose": "assertionMethod"}'
            )
            verification_result = json.loads(result)
            return not verification_result.get("errors")
        except Exception as e:
            logger.debug(f"didkit verification failed: {e}")

    try:
        data = json.loads(vc_json)
        return bool(data and isinstance(data, dict) and "credentialSubject" in data)
    except Exception:
        return False


def issue_vc(
    credential: Dict,
    did: str,
    key: str,
    proof_type: str = "Ed25519Signature2018",
) -> Optional[str]:
    """
    Issue a Verifiable Credential (VC) using didkit.

    This function uses didkit for actual cryptographic signing.
    The DID can be generated by Rust or didkit.

    Args:
        credential: The credential to issue (as a dictionary).
        did: The DID of the issuer.
        key: The private key of the issuer (in JWK format as a string).
        proof_type: The proof type to use.

    Returns:
        The issued VC as a JSON string, or None if issuance fails.
    """
    if not DIDKIT_AVAILABLE:
        mock_vc = dict(credential)
        mock_vc["proof"] = {
            "type": "MockProof",
            "created": "2024-01-01T00:00:00Z",
            "proofPurpose": "assertionMethod",
            "verificationMethod": f"{did}#mock-key",
            "jws": "mock-signature",
        }
        return json.dumps(mock_vc)

    try:
        credential = credential.copy()

        extra_fields = {}
        credential_subject = credential.get("credentialSubject", {})
        if credential_subject:
            for field_name in list(credential_subject.keys()):
                if field_name != "id":
                    extra_fields[field_name] = credential_subject.pop(field_name)

        if isinstance(credential.get("@context"), str):
            credential["@context"] = [credential["@context"]]

        if "https://www.w3.org/2018/credentials/v1" not in credential.get(
            "@context", []
        ):
            credential.setdefault(
                "@context", ["https://www.w3.org/2018/credentials/v1"]
            )

        if "proof" in credential:
            del credential["proof"]

        vm = f"{did}#{did.split(':')[-1]}"
        options = {
            "proofPurpose": "assertionMethod",
            "verificationMethod": vm,
        }

        vc = didkit.issueCredential(
            json.dumps(credential),
            json.dumps(options),
            key,
        )

        if vc and extra_fields:
            vc_dict = json.loads(vc)
            vc_credential_subject = vc_dict.get("credentialSubject", {})
            if vc_credential_subject:
                vc_credential_subject.update(extra_fields)
                vc = json.dumps(vc_dict)

        return vc
    except Exception as e:
        logger.error(f"Failed to issue VC: {e}")
        return None


def generate_key() -> tuple[str, str]:
    """
    Generate a new key pair for DID operations.

    Returns:
        Tuple of (did, key) where key is in JWK format.
    """
    if DIDKIT_AVAILABLE:
        try:
            key = didkit.generateEd25519Key()
            did = didkit.keyToDID("key", key)
            return did, key
        except Exception as e:
            logger.warning(f"didkit key generation failed: {e}")

    import uuid

    did = f"did:key:mock-{uuid.uuid4().hex[:16]}"
    key = json.dumps(
        {
            "kty": "OKP",
            "crv": "Ed25519",
            "x": uuid.uuid4().hex[:32],
            "d": uuid.uuid4().hex[:32],
        }
    )
    return did, key
