"""
Django settings for iyou_name project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    NAME_ALLOWED_HOSTED=(list, []),
)

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = env("NAME_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("NAME_DEBUG")

ALLOWED_HOSTS = env.list("NAME_ALLOWED_HOSTS", default=[])

CSRF_TRUSTED_ORIGINS = env.list(
    "NAME_CSRF_TRUSTED_ORIGINS",
    default=["https://name.iyou.me"],
)

# File upload size limit (10MB)
MAX_FILE_SIZE = 10 * 1024 * 1024  # 10MB in bytes

# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
]

EXTERNAL_APPS = [
    "debug_toolbar",
    "mozilla_django_oidc",
]

OWN_APPS = [
    "apps.accounts",
    "apps.core",
    "apps.upload",
    "apps.browse",
    "apps.hud",
    "apps.charts",
    "apps.users",
    "apps.generator",
    "apps.selector",
    "apps.chart_storage",
]

INSTALLED_APPS = DJANGO_APPS + EXTERNAL_APPS + OWN_APPS

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.core.middleware.OIDCStatePruningMiddleware",
    "apps.core.middleware.SessionCleanupMiddleware",
    "apps.core.rate_limiting.RateLimitMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "apps.accounts.backends.MyOIDCAuthenticationBackend",
]

AUTH_USER_MODEL = "users.CustomUser"

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates"
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.satellite_urls",
                "apps.core.context_processors.genealogy",
            ],
        },
    },
]

# Ecosystem satellite URLs (context processor defaults)
IDP_HOME_URL = "https://iyou.me"
WUN_URL = "https://wun.iyou.me"
POLY_URL = "https://poly.iyou.me"
HIVE_URL = "https://hive.iyou.me"

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    "default": env.db_url(
        "DATABASE_URL",
        default="postgres://iyou_name:iyou_name@localhost:5432/iyou_name",
    )
}

TEST = {
    "NAME": "iyou_name",
}

TEST_RUNNER = "django.test.runner.DiscoverRunner"

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "apps" / "core" / "static",
    BASE_DIR / "apps" / "upload" / "static",
    BASE_DIR / "apps" / "browse" / "static",
    BASE_DIR / "apps" / "hud" / "static",
    BASE_DIR / "apps" / "charts" / "static",
    BASE_DIR / "apps" / "users" / "static",
]

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "debug.log",
            "formatter": "verbose",
        },
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": True,
        },
        "apps.generator": {
            "handlers": ["file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

# Media files (Uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

SESSION_ENGINE = "django.contrib.sessions.backends.db"

# Force exact short-app namespace token to align with ingress web subdomains
APP_NAME_PREFIX = "name"
SESSION_COOKIE_NAME = f"{APP_NAME_PREFIX}_sessionid"
CSRF_COOKIE_NAME = f"{APP_NAME_PREFIX}_csrftoken"
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_TRUSTED_ORIGINS = [f"https://{APP_NAME_PREFIX}.iyou.me"]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# DJANGO DEBUG TOOLBAR SETTINGS
INTERNAL_IPS = ["127.0.0.1", "::1"]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Force environment strings for the Sovereign Identity Provider
IDP_BASE_PUBLIC_URL = env.str("IDP_BASE_PUBLIC_URL", default="https://iyou.me")
IDP_BASE_INTERNAL_URL = env.str("IDP_BASE_INTERNAL_URL", default="http://iyou-idp.identity.svc.cluster.local:8000")

OIDC_OP_AUTHORIZATION_ENDPOINT = f"{IDP_BASE_PUBLIC_URL}/openid/authorize/"
OIDC_OP_TOKEN_ENDPOINT = f"{IDP_BASE_INTERNAL_URL}/openid/token/"
OIDC_OP_USER_ENDPOINT = f"{IDP_BASE_INTERNAL_URL}/openid/userinfo/"
OIDC_OP_JWKS_ENDPOINT = f"{IDP_BASE_INTERNAL_URL}/openid/jwks/"

LOGIN_URL = "oidc_authentication_init"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = f"{IDP_BASE_PUBLIC_URL}/"

# OIDC Relying Party — all values purely from environment
OIDC_RP_CLIENT_ID = env.str("OIDC_RP_CLIENT_ID")
OIDC_RP_CLIENT_SECRET = env.str("OIDC_RP_CLIENT_SECRET")
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_CALLBACK_URL = env.str("OIDC_RP_CALLBACK_URL")

# PKCE — session-backed code verifier for zero-secret auth
OIDC_USE_PKCE = True
OIDC_PKCE_CODE_VERIFIER_SIZE = 64
OIDC_PKCE_CODE_CHALLENGE_METHOD = "S256"
OIDC_MAX_STATES = 50
OIDC_STATE_SIZE = 32
OIDC_NONCE_SIZE = 32

# GrampsWeb Integration
# GENEALOGY_MODE options: "disabled", "grampsweb", "webtrees", "external"
GENEALOGY_MODE = os.environ.get("GENEALOGY_MODE", "disabled")
GENEALOGY_EXTERNAL_URL = os.environ.get("GENEALOGY_EXTERNAL_URL", "")

# GrampsWeb settings (used when GENEALOGY_MODE="grampsweb")
GRAMPSWEB_API_URL = os.environ.get("GRAMPSWEB_API_URL", "")
GRAMPSWEB_API_TOKEN = os.environ.get("GRAMPSWEB_API_TOKEN", "")
GRAMPSWEB_API_TIMEOUT = int(os.environ.get("GRAMPSWEB_API_TIMEOUT", "30"))
GRAMPSWEB_BASE_URL = os.environ.get("GRAMPSWEB_BASE_URL", "")

# WebTrees settings (used when GENEALOGY_MODE="webtrees")
WEBTREES_URL = os.environ.get("WEBTREES_URL", "")
WEBTREES_API_URL = os.environ.get("WEBTREES_API_URL", "")
WEBTREES_API_TOKEN = os.environ.get("WEBTREES_API_TOKEN", "")

# Redis URL for caching
REDIS_URL = os.environ.get("REDIS_URL", "")
