# Generated by Django 5.2.8 on 2025-12-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_parsedgedcomdata_home_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gedcomfile',
            name='home_person_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gedcomfile',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gedcomfile',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gedcomfile',
            name='processing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
