# Generated by Django 6.0 on 2026-02-23 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GedcomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_hash', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('individual_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gedcom_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_used', models.PositiveBigIntegerField(default=0)),
                ('bytes_limit', models.PositiveBigIntegerField(default=524288000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Storage Quota',
                'verbose_name_plural': 'User Storage Quotas',
            },
        ),
        migrations.CreateModel(
            name='ChartBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_hash', models.CharField(max_length=64)),
                ('individual_id', models.CharField(max_length=100)),
                ('generation', models.PositiveSmallIntegerField()),
                ('settings_hash', models.CharField(max_length=32)),
                ('chart_version', models.CharField(max_length=16)),
                ('buffer_file', models.FileField(upload_to='buffers/')),
                ('file_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(default=1950)),
                ('height', models.PositiveIntegerField(default=1950)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_buffers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'gedcom_hash', 'individual_id'], name='chart_stora_user_id_2c8965_idx'), models.Index(fields=['user', 'last_accessed'], name='chart_stora_user_id_535ba0_idx')],
                'unique_together': {('user', 'gedcom_hash', 'individual_id', 'generation')},
            },
        ),
        migrations.CreateModel(
            name='IndividualSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_hash', models.CharField(max_length=64)),
                ('gedcom_name', models.CharField(max_length=255)),
                ('individual_id', models.CharField(max_length=100)),
                ('individual_name', models.CharField(max_length=255)),
                ('settings_json', models.JSONField()),
                ('is_home_person', models.BooleanField(default=False)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Individual Settings',
                'indexes': [models.Index(fields=['user', 'gedcom_hash'], name='chart_stora_user_id_c0c76c_idx'), models.Index(fields=['user', 'gedcom_hash', 'is_home_person'], name='chart_stora_user_id_d3ddd2_idx')],
                'unique_together': {('user', 'gedcom_hash', 'individual_id')},
            },
        ),
        migrations.CreateModel(
            name='UserSettingsPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('settings_json', models.JSONField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
