# Generated by Django 6.0.2 on 2026-03-15 22:21

import apps.chart_storage.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gedcom_hash', models.CharField(max_length=64)),
                ('gedcom_name', models.CharField(max_length=255)),
                ('individual_id', models.CharField(max_length=100)),
                ('individual_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=apps.chart_storage.models.user_photo_upload_path)),
                ('file_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Individual Photos',
                'indexes': [models.Index(fields=['user', 'gedcom_hash'], name='chart_stora_user_id_f372a2_idx')],
                'unique_together': {('user', 'gedcom_hash', 'individual_id')},
            },
        ),
    ]
