# Generated by Django 6.0.2 on 2026-03-15 23:05

import apps.chart_storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart_storage', '0002_individualphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualphoto',
            name='photo',
            field=models.ImageField(max_length=255, upload_to=apps.chart_storage.models.user_photo_upload_path),
        ),
    ]
